name: python-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements-cache.txt'
    - name: Install Python packages
      run: |
        pip install -r requirements-cache.txt
        pip install -e ".[dev,doc,test]"
    - name: Run pre-commit
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Configure lamin
      run: |
        mkdir -p "$HOME/data"
        lamin configure --notion=${{ secrets.NOTION_API_KEY }} --storage "$HOME/data"
    - name: Test with pytest
      run: |
        pytest --nbmake --overwrite docs/guides/*ipynb
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Setup node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
    - name: Install netlify CLI
      run: |
        npm install --save-dev netlify-cli
    - name: Deploy to test site
      if: github.event_name == 'pull_request'
      run: |
        netlify deploy --dir docs/_build/html
    - name: Deploy to production
      if: github.event_name == 'push'
      run: |
        netlify deploy --dir docs/_build/html --prod
